"""Tests for strategy.research_notebook — Research Notebook."""

import json
import os
import tempfile
from pathlib import Path

import pytest

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from strategy.research_notebook import (
    ResearchNote,
    ResearchNotebook,
)


@pytest.fixture
def tmp_dir():
    """Create a temporary directory for testing."""
    tmp = tempfile.mkdtemp()
    yield tmp
    # Cleanup
    import shutil
    shutil.rmtree(tmp, ignore_errors=True)


@pytest.fixture
def notebook(tmp_dir):
    """Create a ResearchNotebook with temp directory."""
    return ResearchNotebook(base_dir=tmp_dir)


# ---- ResearchNote dataclass tests ----

class TestResearchNoteDataclass:
    """Test ResearchNote dataclass."""

    def test_defaults(self):
        note = ResearchNote()
        assert note.date == ""
        assert note.trade_count == 0
        assert note.daily_pl == 0.0
        assert note.hypotheses == []

    def test_to_dict(self):
        note = ResearchNote(
            date="2026-07-02",
            content="Test content",
            market_regime="bullish",
            regime_confidence=0.75,
            rs_leaders=["AAPL (score: 80)"],
            trade_count=5,
            daily_pl=150.0,
            win_rate=80.0,
        )
        d = note.to_dict()
        assert d["date"] == "2026-07-02"
        assert d["market_regime"] == "bullish"
        assert d["regime_confidence"] == 0.75
        assert d["trade_count"] == 5
        assert d["daily_pl"] == 150.0
        assert isinstance(d["rs_leaders"], list)

    def test_to_dict_roundtrip(self):
        note = ResearchNote(
            date="2026-07-02",
            content="Test",
            market_regime="volatile",
            hypotheses=["H1"],
            data_needed=["More data"],
        )
        d = note.to_dict()
        note2 = ResearchNote(**d)
        assert note2.date == note.date
        assert note2.market_regime == note.market_regime
        assert note2.hypotheses == note.hypotheses

    def test_to_markdown_basic(self):
        note = ResearchNote(
            date="2026-07-02",
            content="Market was choppy today.",
            market_regime="volatile",
            regime_confidence=0.60,
        )
        md = note.to_markdown()
        assert "# Research Note" in md
        assert "2026-07-02" in md
        assert "volatile" in md
        assert "Market was choppy today" in md

    def test_to_markdown_with_trades(self):
        note = ResearchNote(
            date="2026-07-02",
            daily_pl=250.00,
            trade_count=10,
            win_rate=70.0,
        )
        md = note.to_markdown()
        assert "$250.00" in md
        assert "**Trade Count:**" in md
        assert "**Win Rate:**" in md

    def test_to_markdown_with_leaders(self):
        note = ResearchNote(
            date="2026-07-02",
            rs_leaders=["AAPL (score: 80)", "NVDA (score: 75)"],
        )
        md = note.to_markdown()
        assert "Relative Strength Leaders" in md
        assert "AAPL" in md
        assert "NVDA" in md

    def test_to_markdown_with_laggards(self):
        note = ResearchNote(
            date="2026-07-02",
            rs_laggards=["TSLA (score: 20)"],
        )
        md = note.to_markdown()
        assert "Relative Strength Laggards" in md
        assert "TSLA" in md

    def test_to_markdown_with_hypotheses(self):
        note = ResearchNote(
            date="2026-07-02",
            hypotheses=["H1: RS stocks win more"],
        )
        md = note.to_markdown()
        assert "Hypotheses" in md
        assert "H1" in md
        assert "testable hypotheses" in md.lower() or "hypotheses" in md.lower()

    def test_to_markdown_with_patterns(self):
        note = ResearchNote(
            date="2026-07-02",
            patterns=["Pattern A observed"],
        )
        md = note.to_markdown()
        assert "Emerging Patterns" in md

    def test_to_markdown_with_confidence(self):
        note = ResearchNote(
            date="2026-07-02",
            confidence="Low",
        )
        md = note.to_markdown()
        assert "Confidence Level" in md
        assert "Low" in md

    def test_to_markdown_with_data_needed(self):
        note = ResearchNote(
            date="2026-07-02",
            data_needed=["Sector data"],
        )
        md = note.to_markdown()
        assert "Additional Data Needed" in md

    def test_to_markdown_footer(self):
        note = ResearchNote(date="2026-07-02")
        md = note.to_markdown()
        assert "Generated by Trade Joe" in md
        assert "Never claims conclusions without supporting evidence" in md


# ---- ResearchNotebook tests ----

class TestResearchNotebookInit:
    """Test ResearchNotebook initialization."""

    def test_creates_notes_dir(self, tmp_dir):
        nb = ResearchNotebook(base_dir=tmp_dir)
        assert (Path(tmp_dir) / "research_notes").exists()

    def test_creates_md_dir(self, tmp_dir):
        nb = ResearchNotebook(base_dir=tmp_dir)
        assert (Path(tmp_dir) / "reports" / "research").exists()

    def test_default_base_dir(self):
        nb = ResearchNotebook()
        assert nb.base_dir.exists()


class TestGenerateDailyNote:
    """Test generate_daily_note method."""

    def test_generate_empty_note(self, notebook):
        note = notebook.generate_daily_note(date="2026-07-02")
        assert note.date == "2026-07-02"
        assert "Limited data" in note.content or note.content

    def test_generate_note_with_regime(self, notebook):
        note = notebook.generate_daily_note(
            date="2026-07-02",
            regime_data={"regime": "bullish", "confidence": 0.80},
        )
        assert note.market_regime == "bullish"
        assert note.regime_confidence == 0.80
        assert "bullish" in note.content

    def test_generate_note_with_performance(self, notebook):
        note = notebook.generate_daily_note(
            date="2026-07-02",
            performance_data={
                "total_trades": 10,
                "total_pl": 500.0,
                "win_rate": 80.0,
                "profit_factor": 2.5,
                "average_winner": 100.0,
                "average_loser": -50.0,
            },
        )
        assert note.trade_count == 10
        assert note.daily_pl == 500.0
        assert note.win_rate == 80.0
        assert "Strong day" in note.content  # win_rate >= 70
        assert "Profit factor: 2.5" in str(note.trade_observations)

    def test_generate_note_average_day(self, notebook):
        note = notebook.generate_daily_note(
            date="2026-07-02",
            performance_data={
                "total_trades": 5,
                "total_pl": 50.0,
                "win_rate": 60.0,
            },
        )
        assert "Average day" in note.content

    def test_generate_note_below_average_day(self, notebook):
        note = notebook.generate_daily_note(
            date="2026-07-02",
            performance_data={
                "total_trades": 5,
                "total_pl": -100.0,
                "win_rate": 20.0,
            },
        )
        assert "Below-average" in note.content

    def test_generate_note_with_rs_data(self, notebook):
        note = notebook.generate_daily_note(
            date="2026-07-02",
            rs_data={
                "all_symbols": [
                    {"symbol": "AAPL", "rs_score": 90.0},
                    {"symbol": "NVDA", "rs_score": 85.0},
                    {"symbol": "TSLA", "rs_score": 30.0},
                ],
            },
        )
        assert any("AAPL" in l for l in note.rs_leaders)
        assert any("TSLA" in l for l in note.rs_laggards)

    def test_generate_note_with_trades(self, notebook):
        trades = [
            {"exit_price": 110.0, "exit_reason": "target", "holding_period_seconds": 3600},
            {"exit_price": 105.0, "exit_reason": "target", "holding_period_seconds": 7200},
        ]
        note = notebook.generate_daily_note(
            date="2026-07-02",
            trades=trades,
        )
        assert any("target" in obs for obs in note.trade_observations)
        assert any("hours" in obs for obs in note.trade_observations)

    def test_generate_note_auto_date(self, notebook):
        note = notebook.generate_daily_note()
        from datetime import datetime
        today = datetime.utcnow().strftime("%Y-%m-%d")
        assert note.date == today


class TestSaveAndLoadNotes:
    """Test saving and loading notes."""

    def test_save_note_creates_json(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            content="Test",
            market_regime="bullish",
        )
        path = notebook.save_note(note)
        assert path.exists()
        assert path.suffix == ".json"

    def test_save_note_creates_markdown(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            content="Test",
        )
        notebook.save_note(note)
        md_path = notebook.md_dir / "2026-07-02.md"
        assert md_path.exists()
        assert "Research Note" in md_path.read_text()

    def test_save_note_json_content(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            content="Market up",
            market_regime="bullish",
            hypotheses=["H1"],
            trade_count=10,
        )
        notebook.save_note(note)
        data = json.loads((notebook.notes_dir / "2026-07-02.json").read_text())
        assert data["date"] == "2026-07-02"
        assert data["content"] == "Market up"
        assert data["market_regime"] == "bullish"
        assert data["hypotheses"] == ["H1"]
        assert data["trade_count"] == 10

    def test_get_recent_notes_empty(self, notebook):
        notes = notebook.get_recent_notes()
        assert notes == []

    def test_get_recent_notes(self, notebook):
        for day in range(1, 6):
            note = ResearchNote(
                date=f"2026-07-{day:02d}",
                content=f"Day {day}",
            )
            notebook.save_note(note)

        notes = notebook.get_recent_notes()
        assert len(notes) >= 5

    def test_get_recent_notes_limit(self, notebook):
        for day in range(1, 11):
            note = ResearchNote(
                date=f"2026-07-{day:02d}",
                content=f"Day {day}",
            )
            notebook.save_note(note)

        notes = notebook.get_recent_notes(limit=3)
        assert len(notes) == 3


class TestPatternDetection:
    """Test _detect_patterns method."""

    def test_no_patterns_empty_note(self, notebook):
        note = ResearchNote(date="2026-07-02")
        patterns = notebook._detect_patterns(note)
        # Should not crash, may return empty or generic patterns
        assert isinstance(patterns, list)

    def test_pattern_rs_leaders_correlation(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            rs_leaders=["AAPL"],
            trade_observations=["Test"],
        )
        patterns = notebook._detect_patterns(note)
        assert any("Relative strength" in p for p in patterns)

    def test_pattern_bullish_positive_pl(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            market_regime="bullish",
            trade_count=10,
            daily_pl=100.0,
        )
        patterns = notebook._detect_patterns(note)
        assert any("bullish" in p for p in patterns)

    def test_pattern_bullish_negative_pl(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            market_regime="bullish",
            trade_count=10,
            daily_pl=-50.0,
        )
        patterns = notebook._detect_patterns(note)
        assert any("Regime alone may not predict" in p or "Negative" in p for p in patterns)


class TestHypothesisGeneration:
    """Test _generate_hypotheses method."""

    def test_hypothesis_with_rs_leaders(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            rs_leaders=["AAPL"],
        )
        hypotheses = notebook._generate_hypotheses(note)
        assert any("relative strength" in h.lower() for h in hypotheses)

    def test_hypothesis_with_regime(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            market_regime="volatile",
        )
        hypotheses = notebook._generate_hypotheses(note)
        assert any("Volatile" in h or "regime" in h.lower() for h in hypotheses)

    def test_hypothesis_with_trades(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            trade_count=10,
        )
        hypotheses = notebook._generate_hypotheses(note)
        assert any("time of day" in h.lower() or "time" in h.lower() for h in hypotheses)


class TestConfidenceAssessment:
    """Test _assess_confidence method."""

    def test_low_confidence_few_trades(self, notebook):
        note = ResearchNote(date="2026-07-02", trade_count=3)
        conf = notebook._assess_confidence(note)
        assert "Low" in conf

    def test_medium_low_confidence(self, notebook):
        note = ResearchNote(date="2026-07-02", trade_count=15)
        conf = notebook._assess_confidence(note)
        assert "Medium-Low" in conf

    def test_medium_confidence(self, notebook):
        note = ResearchNote(date="2026-07-02", trade_count=30)
        conf = notebook._assess_confidence(note)
        assert "Medium" in conf

    def test_medium_high_confidence(self, notebook):
        note = ResearchNote(date="2026-07-02", trade_count=60)
        conf = notebook._assess_confidence(note)
        assert "Medium-High" in conf


class TestDataGapIdentification:
    """Test _identify_data_gaps method."""

    def test_gaps_few_trades(self, notebook):
        note = ResearchNote(date="2026-07-02", trade_count=10)
        gaps = notebook._identify_data_gaps(note)
        assert any("20" in g for g in gaps)  # mentions needing more than 20

    def test_gaps_no_rs(self, notebook):
        note = ResearchNote(date="2026-07-02", trade_count=50)
        gaps = notebook._identify_data_gaps(note)
        assert any("Relative strength" in g for g in gaps)

    def test_gaps_unknown_regime(self, notebook):
        note = ResearchNote(date="2026-07-02", market_regime="unknown")
        gaps = notebook._identify_data_gaps(note)
        assert any("Market regime" in g for g in gaps)

    def test_gaps_always_includes_time_and_sector(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            trade_count=50,
            rs_leaders=["AAPL"],
            market_regime="bullish",
        )
        gaps = notebook._identify_data_gaps(note)
        assert any("time" in g.lower() for g in gaps)
        assert any("sector" in g.lower() for g in gaps)


class TestContentGeneration:
    """Test _generate_content method."""

    def test_content_with_regime(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            market_regime="bullish",
            regime_confidence=0.85,
        )
        content = notebook._generate_content(note)
        assert "bullish" in content

    def test_content_with_high_win_rate(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            trade_count=10,
            win_rate=80.0,
        )
        content = notebook._generate_content(note)
        assert "Strong day" in content

    def test_content_with_average_win_rate(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            trade_count=10,
            win_rate=55.0,
        )
        content = notebook._generate_content(note)
        assert "Average day" in content

    def test_content_with_low_win_rate(self, notebook):
        note = ResearchNote(
            date="2026-07-02",
            trade_count=10,
            win_rate=30.0,
        )
        content = notebook._generate_content(note)
        assert "Below-average" in content

    def test_content_no_data(self, notebook):
        note = ResearchNote(date="2026-07-02")
        content = notebook._generate_content(note)
        assert "Limited data" in content or "collect" in content.lower()

